-
   levent: birth
   etype: baptism
   arole: father
   age: 20y
   limit: GT
   prob: 90
-
   levent: birth
   etype: baptism
   arole: child 
   age: 1
   limit: LT
   prob: 80
-
   levent: birth
   etype: baptism
   arole: child 
   age: 0
   limit: GT
   prob: 100
-
   levent: birth
   etype: baptism
   arole: mother
   age: 18y
   limit: GT
   prob: 90
-
   levent: death
   etype: baptism
   arole: mother
   age: 0y
   limit: GT
   prob: 100  
-
   levent: death
   etype: baptism
   arole: father
   age: 1y
   limit: LT
   prob: 100  
-
   levent: death
   etype: baptism
   arole: child
   age: 0y
   limit: GT
   prob: 100 
-
   levent: death
   etype: baptism
   arole: child
   age: 60y
   limit: LT
   prob: 50 
