

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

glimpse_begin:
    path: /
    controller:  App\Controller\SourceController::showall

glimpse_start:
    path: /glimpses
    controller:  App\Controller\SourceController::showall


glimpse_new:
    path: /glimpse/new/{type}
    controller:  App\Controller\GlimpseController::new


glimpse_show:
    path: /glimpse/show/{gid}
    controller:  App\Controller\GlimpseController::show

glimpse_show_all:
    path: /glimpse/showall/
    controller:  App\Controller\GlimpseController::showall

glimpse_view_all:
    path: /glimpse/showregion/{region}
    controller:  App\Controller\GlimpseController::showregion

glimpse_view_source:
    path: /glimpse/showsource/{sourceid}
    controller:  App\Controller\GlimpseController::showsource




glimpse_edit:
    path: /glimpse/edit/{gid}
    controller:  App\Controller\GlimpseController::edit

glimpse_delete:
    path: /glimpse/delete/{gid}
    controller:  App\Controller\GlimpseController::delete

glimpse_process_edit:
    path: /glimpse/process_edit/{gid}
    controller:  App\Controller\GlimpseController::process_edit


glimpse_delete_role:
   path: /glimpse/deleterole/{gid}/{pref}
   controller:  App\Controller\GlimpseController::delete_role


glimpse_edit_role:
   path: /glimpse/editrole/{gid}/{pref}
   controller:  App\Controller\GlimpseController::edit_role


glimpse_process_edit_role:
   path: /glimpse/process_editrole/{gid}/{aref}
   controller:  App\Controller\GlimpseController::process_editrole


glimpse_delete_predicate:
   path:  /glimpse/role/deletepredicate/{gid}/{aref}/{pref}
   controller:  App\Controller\GlimpseController::delete_predicate


glimpse_filter:
   path:  /glimpse/filter/
   controller:  App\Controller\GlimpseController::filter

glimpse_clearfilter:
   path:  /glimpse/clearsearch/
   controller:  App\Controller\GlimpseController::clearfilter


actor_newactor:
   path:  /actor/newactor/{gid}/{rref}
   controller:  App\Controller\ActorController::newactor


source_all:
   path:  /source/showall
   controller:  App\Controller\SourceController::showall

source_new:
   path:  /source/new
   controller:  App\Controller\SourceController::new


source_process_edit:
    path: /source/process_edit/{sid}
    controller:  App\Controller\SourceController::process_edit


source_edit:
    path: /source/edit/{sid}
    controller:  App\Controller\SourceController::edit

source_show:
    path: /source/show/{sid}
    controller:  App\Controller\SourceController::showone


source_startinput:
    path: /source/startinput/{sourceid}
    controller:  App\Controller\GlimpseController::startinput

source_selectinput:
    path: /source/selectinput/{location}
    controller:  App\Controller\SourceController::selectinput

actor_show_all:
    path: /actor/showall/
    controller:  App\Controller\ActorController::showall

actor_show:
    path: /actor/show/{aid}
    controller:  App\Controller\ActorController::show

actor_new:
    path: /actor/new/
    controller:  App\Controller\ActorController::new

actor_newrelationship:
    path: /actor/newrelationship/{aid}
    controller:  App\Controller\ActorController::newrelationship

actor_process_newrelationship:
    path: /actor/process_newrelationship/{a1ref}
    controller:  App\Controller\ActorController::process_newrelationship

actor_edit:
    path: /actor/edit/{aid}
    controller:  App\Controller\ActorController::edit

actor_editroles:
    path: /actor/editroles/{aid}
    controller:  App\Controller\ActorController::editroles

actor_process_edit:
    path: /actor/process_edit/{aid}
    controller:  App\Controller\ActorController::process_edit


actor_delete:
    path: /actor/delete/{aid}
    controller:  App\Controller\ActorController::delete

actor_addrole:
    path: /actor/addrole/{aid}/{rid}
    controller:  App\Controller\ActorController::addrole

actor_deleterole:
    path: /actor/deleterole/{aid}/{rid}
    controller:  App\Controller\ActorController::deleterole

actor_updatelifeevents:
    path: actor/updatelifeevents/{aid}
    controller:  App\Controller\ActorController::updatelifeevents

actor_merge:
   path: /actor/merge/{aid}/{daid}
   controller:  App\Controller\ActorController::merge

actor_compare:
   path: /actor/compare/{aid}/{daid}
   controller:  App\Controller\ActorController::compare

relation_show_all:
    path: /relation/showall/
    controller:  App\Controller\RelationController::showall

relation_show_one:
    path: /relation/show/{rid}
    controller:  App\Controller\RelationController::showone

relation_addclue:
    path: /relation/addclue/{rid}/{gref}
    controller:  App\Controller\RelationController::addclue

